### ISSUE TITLE
Windows - Failed to fetch container.xml

### ISSUE THREAD

**Issue by comeauac** [mcombeau/epub_downloader#1] opened 2024-06-16 18:21 UTC
The URL is generating incorrectly: it isn't appending a / and instead is converting it to the hex code for backslash, which is %5C
See the full error log below, this happens for any epub.pub URL I enter:

![image](https://github.com/mcombeau/epub_downloader/assets/24308912/22d84f74-6983-4fcf-9931-8c125344f1d0)

**Comment by mcombeau** [comment] 2024-06-22 07:03
Thanks for bringing this issue to my attention. I developed this script for Unix systems and hadn't tested it on Windows. The issue is due to the fact that I'm concatenating the URL and `META-INF/container.xml` with the `os.path` library. This issue was not visible in Unix systems because their system paths use forward slashes `/`, but it is problematic in Windows because Windows uses backslashes '\' for paths.

So, the path resolves as follows on Windows:
```
https://asset.epub.pub/epub/it-by-stephen-king-1.epub\META-INF/container.xml
```
But it should be:
```
https://asset.epub.pub/epub/it-by-stephen-king-1.epub/META-INF/container.xml
```

I'm reworking the script to properly handle URL concatenation and to work on Windows as well.

**Comment by comeauac** [comment] 2024-06-23 01:12
I think there's still an issue with concatenation, but if I run main.py directly then it works great. Thanks for all your hard work!
![image](https://github.com/mcombeau/epub_downloader/assets/24308912/c42c360d-bbcf-42d5-89da-14b3d53cbd78)

**Comment by mcombeau** [comment] 2024-06-23 06:39
I was just about to boot Windows to test it out but you beat me to it! :smile:  Thanks for testing again, I'm glad it works for you.

Ah I see your first command was 
```
python epub_downloader.py https:\\www.epub.pub/...
```
I think the backslashes after https: was the issue in this case. Concatenation seems to work fine for your second command with main.py because the URL was correct with forward slashes (`https://`)

Feel free to pull again for better logs. I will update the README since some things have changed with usage, and close this issue since it seems resolved. Don't hesitate to open another issue if you encounter any other problems.

Thanks again and enjoy!

**Closed as completed by mcombeau** 2024-06-23 06:39 UTC
